site_url: https://zbyszekgos.netlify.app/
logo_url: https://zbyszekgos.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: github
  repo: JMeteor/zbyszekgos.pl
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/media
public_folder: /media

locale: 'pl'

i18n:
  structure: multiple_files
  locales: [pl, en]
  default_locale: pl

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: Ustawienia strony
    name: 'site'
    files:
      - label: Informacje
        name: info
        file: 'content/site/info.json'
        format: json
        editor:
          preview: false
        fields:
          - {
            label: Tytuł strony,
            name: sitename,
            widget: string,
            hint: This is used for the site title
          }
          - {
            label: Opis strony,
            name: sitedescription,
            widget: string,
            hint: This is used as descriptive text for links that link to this site,
          }
          - {
            label: Język strony,
            name: sitelang,
            widget: string,
            pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
          }
          # - { label: Site Email, name: siteemail, widget: string, required: false }

  - name: about
    label: O mnie
    folder: content/about
    create: false
    format: frontmatter
    i18n:
      strucutre: multiple_files
      locales: [pl, en]
    fields:
      - {
        label: Tytuł,
        name: title,
        widget: string,
        required: true,
        i18n: true
      }
      - {
        label: Zdjęcie,
        name: cover,
        widget: image,
        required: true,
      }
      - {
        label: Treść,
        name: body,
        widget: markdown,
        required: true,
        i18n: true
      }
  - name: blog
    label: Aktualności
    folder: content/blog
    create: true
    format: 'frontmatter'
    slug: '{{fields.createdAt}}-{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Data utworzenia', name: 'createdAt', widget: 'datetime', date_format: "YYYY-MM-DD", time_format: false }
      - { label: 'Tytuł', name: 'title', widget: 'string', required: true }
      - { label: 'Opis', name: 'description', widget: 'string', required: false }
      - { label: 'Tekst', name: 'body', widget: 'markdown', required: false }
  - name: projects
    label: Projekty
    label_singular: Projekt
    folder: content/projects
    create: true
    format: frontmatter
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    i18n:
      structure: multiple_files
      locales: [pl, en]
    fields:
      - {
        label: Kategoria,
        name: category,
        widget: select,
        default: misc,
        options: [
          { label: Miejska, value: outdoor },
          { label: Portret, value: portraits },
          { label: Sakralna, value: sacral },
          { label: Inna, value: misc },
        ],
      }
      - {
        label: Materiał,
        name: material,
        widget: select,
        default: bronze,
        options: [
          { label: Brąz, value: bronze },
          { label: Marmur, value: marble },
          { label: Kamień, value: stone },
          { label: Drewno, value: wood },
        ],
      }
      - {
        label: Tytuł,
        name: title,
        widget: string,
        required: true,
        i18n: true,
      }
      - {
        label: Opis,
        name: description,
        widget: string,
        required: false,
        i18n: true,
      }
      - {
        label: Okładka,
        name: cover,
        widget: image,
        required: false,
        allow_multiple: false,
      }
      - {
        label: Treść,
        name: body,
        widget: markdown,
        required: false,
        i18n: true,
      }
      - {
        label: Galeria zdjęć,
        name: gallery,
        widget: list,
        required: false,
        summary: '{{fields.image}}',
        field: {
          label: Zdjęcie,
          name: image,
          widget: image,
        },
      }
